backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Index"
        name: "index"
        fields:
          - {
              label: Groups,
              name: groups,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  {
                    label: Subgroups,
                    name: subgroups,
                    widget: list,
                    fields:
                      [{ label: Subtitle, name: subtitle, widget: string }],
                  },
                ],
            }
